language: node_js

env:
  - CXX=g++-4.8

node_js:
  - 8
  - 10
  - 11

sudo: required

notifications:
  email:
    - lilleman@larvit.se

before_install:
  - $CXX --version

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

services:
  - rabbitmq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script: env AMQP_CONFFILE=amqp_travis.json mocha
